services:
  cf-best-domain:
    image: ghcr.io/hideinmatrix/cf-best-domain:latest
    container_name: cf-best-domain
    restart: unless-stopped
    command:
      - -update
      - -interval
      - ${CFBD_INTERVAL:-30m}
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
    read_only: true
    security_opt:
      - no-new-privileges:true
